//! Contains modules for individual server implementations

use std::convert::Infallible;
use futures::Sink;
use crate::Rpc;

/// Helpers for serving a service from an axum server
#[cfg(feature = "axum")]
pub mod axum;

/// This trait describes a handler which takes a request and calls the appropriate method of
/// an underlying server implementation, then builds and returns the response
///
/// Implementations are generated by the `#[rpc]` macro
pub trait Handler: Send {
    /// The Rpc service served by this handler
    type Rpc: Rpc;
    /// takes the request and returns a response, see [trait documentation](Self) for details
    fn handle(
        &self,
        request: <Self::Rpc as Rpc>::Request,
    ) -> impl Future<Output = <Self::Rpc as Rpc>::Response> + Send;
    /// takes the request and returns a response, see [trait documentation](Self) for details
    fn handle_stream_response<S: Sink<<Self::Rpc as Rpc>::Response, Error = Infallible> + Send + 'static>(
        &self,
        request: <Self::Rpc as Rpc>::Request,
        sink: S,
    ) -> impl Future<Output = ()> + Send;
}
